Using PuLP with pandas and binary constraints to solve a scheduling problem
In this example, we’ll be solving a scheduling problem. We have 2 offshore production plants in 2 locations and an estimated demand for our products.

We want to produce a schedule of production from both plants that meets our demand with the lowest cost.

A factory can be in 2 states:

Off – Producing zero units

On – Producing between its minimum and maximum production capacities.


Both factories have fixed costs, that are incurred as long as the factory is on, and variable costs, a cost per unit of production. These vary month by month.

We also know that factory B is down for maintenance in month 5.

We’ll start by importing our data.

In [2]:
import pandas as pd
import pulp

In [3]:
factories = pd.DataFrame.from_csv('factory_variables.csv', index_col=['Month', 'Factory'])
factories

C:\Users\shakib\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

               Max_Capacity  Min_Capacity  Variable_Costs  Fixed_Costs
Month Factory
1     A              100000         20000              10          500
      B               50000         20000               5          600
2     A              110000         20000              11          500
      B               55000         20000               4          600
3     A              120000         20000              12          500
      B               60000         20000               3          600
4     A              145000         20000               9          500
      B              100000         20000               5          600
5     A              160000         20000               8          500
      B                   0             0               0            0
6     A              140000         20000               8          500
      B               70000         20000               6          600
7     A              155000         20000               5          500
      B               60000         20000               4          600
8     A              200000         20000               7          500
      B              100000         20000               6          600
9     A              210000         20000               9          500
      B              100000         20000               8          600
10    A              197000         20000              10          500
      B              100000         20000              11          600
11    A               80000         20000               8          500
      B              120000         20000              10          600
12    A              150000         20000               8          500
      B              150000         20000              12          600

In [4]:
demand = pd.DataFrame.from_csv('monthly_demand.csv', index_col=['Month'])

C:\Users\shakib\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.

In [5]:
demand

       Demand
Month
1      120000
2      100000
3      130000
4      130000
5      140000
6      130000
7      150000
8      170000
9      200000
10     190000
11     140000
12     100000

In [20]:
factories.index

MultiIndex(levels=[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], ['A', 'B']],
           codes=[[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]],
           names=['Month', 'Factory'])

In [6]:
production = pulp.LpVariable.dicts("production",
                                     ((month, factory) for month, factory in factories.index),
                                     lowBound=0,
                                     cat='Integer')

In [7]:
production

{(1, 'A'): production_(1,_'A'),
 (1, 'B'): production_(1,_'B'),
 (2, 'A'): production_(2,_'A'),
 (2, 'B'): production_(2,_'B'),
 (3, 'A'): production_(3,_'A'),
 (3, 'B'): production_(3,_'B'),
 (4, 'A'): production_(4,_'A'),
 (4, 'B'): production_(4,_'B'),
 (5, 'A'): production_(5,_'A'),
 (5, 'B'): production_(5,_'B'),
 (6, 'A'): production_(6,_'A'),
 (6, 'B'): production_(6,_'B'),
 (7, 'A'): production_(7,_'A'),
 (7, 'B'): production_(7,_'B'),
 (8, 'A'): production_(8,_'A'),
 (8, 'B'): production_(8,_'B'),
 (9, 'A'): production_(9,_'A'),
 (9, 'B'): production_(9,_'B'),
 (10, 'A'): production_(10,_'A'),
 (10, 'B'): production_(10,_'B'),
 (11, 'A'): production_(11,_'A'),
 (11, 'B'): production_(11,_'B'),
 (12, 'A'): production_(12,_'A'),
 (12, 'B'): production_(12,_'B')}

In [8]:
factory_status = pulp.LpVariable.dicts("factory_status",
                                     ((month, factory) for month, factory in factories.index),
                                     cat='Binary')

In [9]:
factory_status

{(1, 'A'): factory_status_(1,_'A'),
 (1, 'B'): factory_status_(1,_'B'),
 (2, 'A'): factory_status_(2,_'A'),
 (2, 'B'): factory_status_(2,_'B'),
 (3, 'A'): factory_status_(3,_'A'),
 (3, 'B'): factory_status_(3,_'B'),
 (4, 'A'): factory_status_(4,_'A'),
 (4, 'B'): factory_status_(4,_'B'),
 (5, 'A'): factory_status_(5,_'A'),
 (5, 'B'): factory_status_(5,_'B'),
 (6, 'A'): factory_status_(6,_'A'),
 (6, 'B'): factory_status_(6,_'B'),
 (7, 'A'): factory_status_(7,_'A'),
 (7, 'B'): factory_status_(7,_'B'),
 (8, 'A'): factory_status_(8,_'A'),
 (8, 'B'): factory_status_(8,_'B'),
 (9, 'A'): factory_status_(9,_'A'),
 (9, 'B'): factory_status_(9,_'B'),
 (10, 'A'): factory_status_(10,_'A'),
 (10, 'B'): factory_status_(10,_'B'),
 (11, 'A'): factory_status_(11,_'A'),
 (11, 'B'): factory_status_(11,_'B'),
 (12, 'A'): factory_status_(12,_'A'),
 (12, 'B'): factory_status_(12,_'B')}

In [10]:
model = pulp.LpProblem("Cost minimising scheduling problem", pulp.LpMinimize)

In [19]:
model += pulp.lpSum([ production[month, factory] * factories.loc[(month, factory), 'Variable_Costs'] for (month, factory) in factories.index]
    + [factory_status[month, factory] * factories.loc[(month, factory), 'Fixed_Costs'] for (month, factory) in factories.index]
)

C:\Users\shakib\Anaconda3\lib\site-packages\pulp\pulp.py:1349: UserWarning: Overwriting previously set objective.
  warnings.warn("Overwriting previously set objective.")

In [12]:
# Production in any month must be equal to demand
months = demand.index
for month in months:
    model += production[(month, 'A')] + production[(month, 'B')] == demand.loc[month, 'Demand']

In [13]:
# Production in any month must be between minimum and maximum capacity, or zero.
for month, factory in factories.index:
    min_production = factories.loc[(month, factory), 'Min_Capacity']
    max_production = factories.loc[(month, factory), 'Max_Capacity']
    model += production[(month, factory)] >= min_production * factory_status[month, factory]
    model += production[(month, factory)] <= max_production * factory_status[month, factory]

In [14]:
# Factory B is off in May
model += factory_status[5, 'B'] == 0
model += production[5, 'B'] == 0

In [15]:
model.solve()
pulp.LpStatus[model.status]

'Optimal'

In [21]:
print(model)

Cost minimising scheduling problem:
MINIMIZE
500*factory_status_(1,_'A') + 600*factory_status_(1,_'B') + 500*factory_status_(10,_'A') + 600*factory_status_(10,_'B') + 500*factory_status_(11,_'A') + 600*factory_status_(11,_'B') + 500*factory_status_(12,_'A') + 600*factory_status_(12,_'B') + 500*factory_status_(2,_'A') + 600*factory_status_(2,_'B') + 500*factory_status_(3,_'A') + 600*factory_status_(3,_'B') + 500*factory_status_(4,_'A') + 600*factory_status_(4,_'B') + 500*factory_status_(5,_'A') + 500*factory_status_(6,_'A') + 600*factory_status_(6,_'B') + 500*factory_status_(7,_'A') + 600*factory_status_(7,_'B') + 500*factory_status_(8,_'A') + 600*factory_status_(8,_'B') + 500*factory_status_(9,_'A') + 600*factory_status_(9,_'B') + 10*production_(1,_'A') + 5*production_(1,_'B') + 10*production_(10,_'A') + 11*production_(10,_'B') + 8*production_(11,_'A') + 10*production_(11,_'B') + 8*production_(12,_'A') + 12*production_(12,_'B') + 11*production_(2,_'A') + 4*production_(2,_'B') + 12*production_(3,_'A') + 3*production_(3,_'B') + 9*production_(4,_'A') + 5*production_(4,_'B') + 8*production_(5,_'A') + 8*production_(6,_'A') + 6*production_(6,_'B') + 5*production_(7,_'A') + 4*production_(7,_'B') + 7*production_(8,_'A') + 6*production_(8,_'B') + 9*production_(9,_'A') + 8*production_(9,_'B') + 0
SUBJECT TO
_C1: production_(1,_'A') + production_(1,_'B') = 120000

_C2: production_(2,_'A') + production_(2,_'B') = 100000

_C3: production_(3,_'A') + production_(3,_'B') = 130000

_C4: production_(4,_'A') + production_(4,_'B') = 130000

_C5: production_(5,_'A') + production_(5,_'B') = 140000

_C6: production_(6,_'A') + production_(6,_'B') = 130000

_C7: production_(7,_'A') + production_(7,_'B') = 150000

_C8: production_(8,_'A') + production_(8,_'B') = 170000

_C9: production_(9,_'A') + production_(9,_'B') = 200000

_C10: production_(10,_'A') + production_(10,_'B') = 190000

_C11: production_(11,_'A') + production_(11,_'B') = 140000

_C12: production_(12,_'A') + production_(12,_'B') = 100000

_C13: - 20000 factory_status_(1,_'A') + production_(1,_'A') >= 0

_C14: - 100000 factory_status_(1,_'A') + production_(1,_'A') <= 0

_C15: - 20000 factory_status_(1,_'B') + production_(1,_'B') >= 0

_C16: - 50000 factory_status_(1,_'B') + production_(1,_'B') <= 0

_C17: - 20000 factory_status_(2,_'A') + production_(2,_'A') >= 0

_C18: - 110000 factory_status_(2,_'A') + production_(2,_'A') <= 0

_C19: - 20000 factory_status_(2,_'B') + production_(2,_'B') >= 0

_C20: - 55000 factory_status_(2,_'B') + production_(2,_'B') <= 0

_C21: - 20000 factory_status_(3,_'A') + production_(3,_'A') >= 0

_C22: - 120000 factory_status_(3,_'A') + production_(3,_'A') <= 0

_C23: - 20000 factory_status_(3,_'B') + production_(3,_'B') >= 0

_C24: - 60000 factory_status_(3,_'B') + production_(3,_'B') <= 0

_C25: - 20000 factory_status_(4,_'A') + production_(4,_'A') >= 0

_C26: - 145000 factory_status_(4,_'A') + production_(4,_'A') <= 0

_C27: - 20000 factory_status_(4,_'B') + production_(4,_'B') >= 0

_C28: - 100000 factory_status_(4,_'B') + production_(4,_'B') <= 0

_C29: - 20000 factory_status_(5,_'A') + production_(5,_'A') >= 0

_C30: - 160000 factory_status_(5,_'A') + production_(5,_'A') <= 0

_C31: production_(5,_'B') >= 0

_C32: production_(5,_'B') <= 0

_C33: - 20000 factory_status_(6,_'A') + production_(6,_'A') >= 0

_C34: - 140000 factory_status_(6,_'A') + production_(6,_'A') <= 0

_C35: - 20000 factory_status_(6,_'B') + production_(6,_'B') >= 0

_C36: - 70000 factory_status_(6,_'B') + production_(6,_'B') <= 0

_C37: - 20000 factory_status_(7,_'A') + production_(7,_'A') >= 0

_C38: - 155000 factory_status_(7,_'A') + production_(7,_'A') <= 0

_C39: - 20000 factory_status_(7,_'B') + production_(7,_'B') >= 0

_C40: - 60000 factory_status_(7,_'B') + production_(7,_'B') <= 0

_C41: - 20000 factory_status_(8,_'A') + production_(8,_'A') >= 0

_C42: - 200000 factory_status_(8,_'A') + production_(8,_'A') <= 0

_C43: - 20000 factory_status_(8,_'B') + production_(8,_'B') >= 0

_C44: - 100000 factory_status_(8,_'B') + production_(8,_'B') <= 0

_C45: - 20000 factory_status_(9,_'A') + production_(9,_'A') >= 0

_C46: - 210000 factory_status_(9,_'A') + production_(9,_'A') <= 0

_C47: - 20000 factory_status_(9,_'B') + production_(9,_'B') >= 0

_C48: - 100000 factory_status_(9,_'B') + production_(9,_'B') <= 0

_C49: - 20000 factory_status_(10,_'A') + production_(10,_'A') >= 0

_C50: - 197000 factory_status_(10,_'A') + production_(10,_'A') <= 0

_C51: - 20000 factory_status_(10,_'B') + production_(10,_'B') >= 0

_C52: - 100000 factory_status_(10,_'B') + production_(10,_'B') <= 0

_C53: - 20000 factory_status_(11,_'A') + production_(11,_'A') >= 0

_C54: - 80000 factory_status_(11,_'A') + production_(11,_'A') <= 0

_C55: - 20000 factory_status_(11,_'B') + production_(11,_'B') >= 0

_C56: - 120000 factory_status_(11,_'B') + production_(11,_'B') <= 0

_C57: - 20000 factory_status_(12,_'A') + production_(12,_'A') >= 0

_C58: - 150000 factory_status_(12,_'A') + production_(12,_'A') <= 0

_C59: - 20000 factory_status_(12,_'B') + production_(12,_'B') >= 0

_C60: - 150000 factory_status_(12,_'B') + production_(12,_'B') <= 0

_C61: factory_status_(5,_'B') = 0

_C62: production_(5,_'B') = 0

VARIABLES
0 <= factory_status_(1,_'A') <= 1 Integer
0 <= factory_status_(1,_'B') <= 1 Integer
0 <= factory_status_(10,_'A') <= 1 Integer
0 <= factory_status_(10,_'B') <= 1 Integer
0 <= factory_status_(11,_'A') <= 1 Integer
0 <= factory_status_(11,_'B') <= 1 Integer
0 <= factory_status_(12,_'A') <= 1 Integer
0 <= factory_status_(12,_'B') <= 1 Integer
0 <= factory_status_(2,_'A') <= 1 Integer
0 <= factory_status_(2,_'B') <= 1 Integer
0 <= factory_status_(3,_'A') <= 1 Integer
0 <= factory_status_(3,_'B') <= 1 Integer
0 <= factory_status_(4,_'A') <= 1 Integer
0 <= factory_status_(4,_'B') <= 1 Integer
0 <= factory_status_(5,_'A') <= 1 Integer
0 <= factory_status_(5,_'B') <= 1 Integer
0 <= factory_status_(6,_'A') <= 1 Integer
0 <= factory_status_(6,_'B') <= 1 Integer
0 <= factory_status_(7,_'A') <= 1 Integer
0 <= factory_status_(7,_'B') <= 1 Integer
0 <= factory_status_(8,_'A') <= 1 Integer
0 <= factory_status_(8,_'B') <= 1 Integer
0 <= factory_status_(9,_'A') <= 1 Integer
0 <= factory_status_(9,_'B') <= 1 Integer
0 <= production_(1,_'A') Integer
0 <= production_(1,_'B') Integer
0 <= production_(10,_'A') Integer
0 <= production_(10,_'B') Integer
0 <= production_(11,_'A') Integer
0 <= production_(11,_'B') Integer
0 <= production_(12,_'A') Integer
0 <= production_(12,_'B') Integer
0 <= production_(2,_'A') Integer
0 <= production_(2,_'B') Integer
0 <= production_(3,_'A') Integer
0 <= production_(3,_'B') Integer
0 <= production_(4,_'A') Integer
0 <= production_(4,_'B') Integer
0 <= production_(5,_'A') Integer
0 <= production_(5,_'B') Integer
0 <= production_(6,_'A') Integer
0 <= production_(6,_'B') Integer
0 <= production_(7,_'A') Integer
0 <= production_(7,_'B') Integer
0 <= production_(8,_'A') Integer
0 <= production_(8,_'B') Integer
0 <= production_(9,_'A') Integer
0 <= production_(9,_'B') Integer

In [16]:
output = []
for month, factory in production:
    var_output = {
        'Month': month,
        'Factory': factory,
        'Production': production[(month, factory)].varValue,
        'Factory Status': factory_status[(month, factory)].varValue
    }
    output.append(var_output)
output_df = pd.DataFrame.from_records(output).sort_values(['Month', 'Factory'])
output_df.set_index(['Month', 'Factory'], inplace=True)
output_df

               Factory Status  Production
Month Factory
1     A                   1.0     70000.0
      B                   1.0     50000.0
2     A                   1.0     45000.0
      B                   1.0     55000.0
3     A                   1.0     70000.0
      B                   1.0     60000.0
4     A                   1.0     30000.0
      B                   1.0    100000.0
5     A                   1.0    140000.0
      B                   0.0         0.0
6     A                   1.0     60000.0
      B                   1.0     70000.0
7     A                   1.0     90000.0
      B                   1.0     60000.0
8     A                   1.0     70000.0
      B                   1.0    100000.0
9     A                   1.0    100000.0
      B                   1.0    100000.0
10    A                   1.0    190000.0
      B                   0.0         0.0
11    A                   1.0     80000.0
      B                   1.0     60000.0
12    A                   1.0    100000.0
      B                   0.0         0.0

In [17]:
# Print our objective function value (Total Costs)
print(pulp.value(model.objective))

12906400.0

In [ ]:
tt